version: '3.8'
services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ../backend/database.db:/app/database.db

  frontend:
    build:
      context: ../frontend/my-app
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE=http://backend:8000
    depends_on:
      - backend
